// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Meridian_BorrowResources_FullMethodName = "/proto.Meridian/BorrowResources"
)

// MeridianClient is the client API for Meridian service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeridianClient interface {
	BorrowResources(ctx context.Context, in *BorrowResourcesReq, opts ...grpc.CallOption) (*BorrowResourcesResp, error)
}

type meridianClient struct {
	cc grpc.ClientConnInterface
}

func NewMeridianClient(cc grpc.ClientConnInterface) MeridianClient {
	return &meridianClient{cc}
}

func (c *meridianClient) BorrowResources(ctx context.Context, in *BorrowResourcesReq, opts ...grpc.CallOption) (*BorrowResourcesResp, error) {
	out := new(BorrowResourcesResp)
	err := c.cc.Invoke(ctx, Meridian_BorrowResources_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeridianServer is the server API for Meridian service.
// All implementations must embed UnimplementedMeridianServer
// for forward compatibility
type MeridianServer interface {
	BorrowResources(context.Context, *BorrowResourcesReq) (*BorrowResourcesResp, error)
	mustEmbedUnimplementedMeridianServer()
}

// UnimplementedMeridianServer must be embedded to have forward compatible implementations.
type UnimplementedMeridianServer struct {
}

func (UnimplementedMeridianServer) BorrowResources(context.Context, *BorrowResourcesReq) (*BorrowResourcesResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BorrowResources not implemented")
}
func (UnimplementedMeridianServer) mustEmbedUnimplementedMeridianServer() {}

// UnsafeMeridianServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeridianServer will
// result in compilation errors.
type UnsafeMeridianServer interface {
	mustEmbedUnimplementedMeridianServer()
}

func RegisterMeridianServer(s grpc.ServiceRegistrar, srv MeridianServer) {
	s.RegisterService(&Meridian_ServiceDesc, srv)
}

func _Meridian_BorrowResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BorrowResourcesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeridianServer).BorrowResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Meridian_BorrowResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeridianServer).BorrowResources(ctx, req.(*BorrowResourcesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Meridian_ServiceDesc is the grpc.ServiceDesc for Meridian service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Meridian_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Meridian",
	HandlerType: (*MeridianServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BorrowResources",
			Handler:    _Meridian_BorrowResources_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
